### ISSUE TITLE
How to work

### ISSUE THREAD

**Issue by piark** [arnaud-carre/lz4-68k#2]
Hello,

I would be very happy to be use this routine on my amiga,
unfortunately I tried to compress data on pc, and the routine crashes before the end (on normal routine, freeze and need reboot, crash on a jmp instruction ), and does not restore the original data at all.
i have tried java lz4 compressor and command line linux lz4 command (with piped stream, no file like this : cat file | lz4 > out.lz4 ), without success.

Can you help me please and  explain to me what you do to compress your datas ?

thanks.
best regards.

**Comment by piark** [comment]
Auto solved,
need to use BLOCK compression (not other)
in java, using apache commons compression, with LZ4 block compression routine, and it's magic work.

Can i suggest to you include on wiki for your github , examples of compression (tools for windows, linux, mac) and parameters ?
thanks,
have a nice day!
regards.

**Comment by piark** [comment]
Bug found, on some compressed files.
It's work on a small file (text file, in fact, the asm amiga source code), not on a bigger (a binary file with 409600 bytes) , i dont know if the size is the cause of the fault.
request me to get the file if you needs.
thanks.

**Comment by arnaud-carre** [comment]
sorry just read your message now... My code is supposed to depack any LZ4 compliant data (whatever the size). What kind of "issue" do you have on large file?

**Comment by asimilon** [comment]
I am also having some issues with this.

vlink complains when trying to use [lz4_fastest.asm](https://github.com/arnaud-carre/lz4-68k/blob/master/lz4_fastest.asm), I can check the specific error if needed.

vasmm68k_mot does not like this in [lz4_normal.asm](https://github.com/arnaud-carre/lz4-68k/blob/master/lz4_normal.asm)
```
repeat	15
{
	move.b	(a0)+,(a1)+
}
```

so I switched it for:
```
rept 15
	move.b	(a0)+,(a1)+
endr
```
which lets it compile.

I used `brew` to  install `lz4` command line tool
```
$ lz4 --help
*** LZ4 command line interface 64-bits v1.9.3, by Yann Collet ***
```

and just compress my data with no special arguments.

I tried to decompress with the depacked data overlapping the packed data like this:

```
PACKED_SIZE = 6755
DEPACK_SPACE = 60416-PACKED_SIZE

depacked:
    dcb.b DEPACK_SPACE,0
packed:
    INCBIN "packed_data.lz4"
...
    lea packed,a0
    lea depacked,a1
    move.l #PACKED_SIZE,d0
    bsr lz4_depack
```
but this crashes after a little while.

I also tried not overlapping the depacked and packed data (although my understanding is that lz4 should support overlapping) and it doesn't crash but never exits `lz4_depack` and stomps over memory.

Should I be setting some specific arguments for the lz4 command line utility?

**Comment by asimilon** [comment]
I've somewhat solved this (a bit!)

I realised that the block size passed in `d0` is not the size of the packed data, but instead something that can be set in the lz4 command line utility, so if I use:
```
$ lz4 -B256 input_file
```
and pass 256 in d0 I at least have no crashes any more or memory getting destroyed.

Unfortunately it's not actually decompressing the data correctly, so I'm still a bit stuck.  I can provide the problematic file if required.

**Comment by arnaud-carre** [comment]
did you pack data using this right command line option like specified here: https://github.com/arnaud-carre/lz4-68k#lz4-frame
Also don't forget to use lz4_frame.asm ( https://github.com/arnaud-carre/lz4-68k/blob/master/lz4_frame.asm )
lz4.exe produce a lz4 stream with a header. lz4_frame knows how to skip header
