### ISSUE TITLE
license

### ISSUE THREAD

**Issue by rvalles** [arnaud-carre/lz4-68k#3]
Hi,

This code would definitely be useful in amigaXfer (MIT licensed project of mine), particularly with slower baudrates or faster CPUs.

But copyright law is what it is, so I can't just take it and use it w/o a license. Would you consider adding some sort of permissive license to this?

Regards.

**Comment by arnaud-carre** [comment]
Hi!

Of course you can use my LZ4 fast depacker code. I'm not into license at all so I don't know what the best way to proceed. What kind of "license" file should I put in the LZ4 repo so anyone can use it?

cheers

Arnaud

**Comment by rvalles** [comment]
Hi,

Ultimately, the reason a license is needed at all is that copyright law is painfully complicated, and by default nothing is allowed, so licenses codify your intent in a way that has legal value. They also tend to include a legal limitation of responsibility, which I consider VERY desirable. Just imagine being sued because e.g. a derivative of your code failed in some way and caused someone economical damages. (!)

All you would need to make github happy is to include a LICENSE or LICENSE.txt file from a list that it can recognize; I have looked at github's docs to see which ones they actually auto-recognize/recommend:

https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

I personally tend to [use MIT](https://github.com/rvalles/pyamigadebug/blob/master/LICENSE) because it is one of the simplest and most permissive out there, but there's plenty to pick from.

Cheers,
Roc

**Comment by arnaud-carre** [comment]
just added MIT license file. I guess it's ok?

**Comment by rvalles** [comment]
> just added MIT license file. I guess it's ok?

Absolutely. Github recognizes it at such, too.
